### PR TITLE
Relaxed version check for compatibility with Laravel 5.6+

### PR DESCRIPTION
**Pull request by hossein**
Tested with Laravel 5.8's default SparkPost API implementation.

### CODE REVIEW

**Comment by spaceemotion** [comment]
Sorry for not seeing this earlier. Seems like I don't get notifications for my own repositories....  Will try to merge and publish this as soon as I am able. Thanks for the fix!

**Comment by hossein** [comment]
Hi; thanks for the effort and thought you put into this library! And thanks for merging.

Just my 2 cents; Maybe add some note to the Read Me file explaining that users should test the compatibility with future laravel versions, if you no longer actively test and use this library.

**Comment by spaceemotion** [comment]
I actually still use it (sending thousands of mails every week), but the App i have is still on 5.5 (due to it being the LTS release) :/

**Comment by hossein** [comment]
Staying on LTS is pretty logical; good luck. :+1:

**Pull request merged**
